management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

chat:
  exchanges:
    input: "output-messages"
    old-messages: "old-message-requests"

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # WILL BE REMOVED WHEN LIQUIBASE IS RUNNING
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/message-push-api
    username: postgres
    password: postgres
  application:
    name: "message-push-api"
  mvc:
    async:
      request-timeout: -1